function sys = mylinearize(io,op)
% MYLINEARIZE Linearize the Simulink model - pidControllerAltitude2023a.
%
% SYS = MYLINEARIZE(IO,OP) linearizes the Simulink model pidControllerAltitude2023a
% using the analysis I/Os IO about the operating point OP.

% MATLAB(R) file generated by MATLAB(R) 9.14 and Simulink Control Design (TM) 7.0.
%
% Generated on: 25-Nov-2024 11:37:01

%% Specify the model name
model = 'pidControllerAltitude2023a';

%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)

