%% Exact linearization of the Simulink model pidControllerAltitude2023aSubsystems
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.14 and Simulink Control Design (TM) 7.0.
%
% Generated on: 25-Nov-2024 10:22:43

%% Specify the model name
model = 'pidControllerAltitude2023aSubsystems';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)

