
% Define the horn ridge antenna with specified parameters
ant = hornRidge('FlareWidth',270e-3, ...
                'FlareHeight',146.2e-3, ...
                'FlareLength',225e-3, ...
                'NumFlares',2, ...
                'RidgeGap',1e-3, ...
                'Length',10e-3, ...
                'Height',40e-3, ...
                'Width',40e-3, ...
                'FeedOffset',[0.002 0], ...
                'RidgeLength',5e-3, ...
                'RidgeWidth',10e-3);

% Display the antenna structure
show(ant);

% Set the frequency for the radiation pattern (example: 10 GHz)
frequency = 10e9;  % in Hz

% Plot the radiation pattern in 3D
figure;
pattern(ant, frequency);

% 2D Radiation Pattern Cut at Azimuth = 0 degrees
% Note: Here, we specify 0 degrees for azimuth and scan over elevation
figure;
pattern(ant, frequency, -180:1:180, 0);  % Sweeps through elevation at azimuth = 0

% Alternatively, 2D Pattern Cut at Elevation = 0 degrees
figure;
pattern(ant, frequency, 0, -180:1:180);  % Sweeps through azimuth at elevation = 0
